name: Upload Image from URL to GitHub

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'URL of the image to upload'
        required: true
        type: string
      file_name:
        description: 'Name for the uploaded file (e.g., image.png)'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download image from URL
        run: |
          curl -o ${{ github.event.inputs.file_name }} ${{ github.event.inputs.image_url }}
          echo "Downloaded image: ${{ github.event.inputs.file_name }}"

      - name: Commit and push to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.event.inputs.file_name }}
          git commit -m "Uploaded image ${{ github.event.inputs.file_name }} from URL"
          git push origin HEAD
          
