name: Upload Image to GitHub

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the image to upload'
        required: true

jobs:
  upload-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload image to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading image..."
          cp ${{ github.event.inputs.file_path }} ./uploaded_image
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Uploaded new image via workflow"
          git push origin HEAD
          
